name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-and-import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install package
        run: |
          python -m pip install -U pip
          python -m pip install -e . ruff
      - name: Lint (format check)
        run: |
          python -m ruff format --check .
      - name: Import smoke tests
        run: |
          python - << 'PY'
          import importlib
          mods = [
            'vibevoice',
            'vibevoice.modular.modeling_vibevoice_inference',
            'vibevoice.processor.vibevoice_processor',
            'vibevoice.modular.modular_vibevoice_text_tokenizer',
          ]
          for m in mods:
              importlib.import_module(m)
              print('OK', m)
          PY
